/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import java.awt.Color;
import javax.swing.JPanel;
import ComboBoxCustom.ComboBoxSugestion;
import static UI.Dashboard.content;
import dataaccess.*;
import defaultPackage.App;
import java.awt.BorderLayout;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author a
 */
public class UpBooks extends javax.swing.JPanel {

    private String[] editoriales;
    private String[] tipo;
    boolean edition;
    String origId;
    /**
     * Creates new form Principal
     */
    public UpBooks() {
        initComponents();
        CboxEditorial.addItem("Sin editorial");
        consultarTipos();
        consultarEditoriales();
        edition = false;
    }
    
    public UpBooks(String bid, String btitle, String bdate, String bauthor, String bcategory, String bedit, String blang, String bpages, String bdesc, String bejem, String bstock, String bavai){
        initComponents();
        
        edition = true;
       
        
        origId = bid;
       
        title.setText(btitle);
        
        authors.setText(bcategory);
        isbn.setText(bedit);
        
        stock.setText(bpages);  
        jLabel1.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        authors = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        isbn = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        Text10 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Text11 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text12 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        CboxRecurso = new ComboBoxCustom.ComboBoxSugestion();
        CboxEditorial = new ComboBoxCustom.ComboBoxSugestion();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Subir nuevo Libro");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        button.setBackground(new java.awt.Color(16, 152, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Tipo de recurso");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        title.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setText("Ingrese el Título");
        title.setBorder(null);
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(34, 184, 207));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 10));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Autores");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        authors.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        authors.setForeground(new java.awt.Color(102, 102, 102));
        authors.setText("Ingrese nombre de autores");
        authors.setBorder(null);
        authors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                authorsMousePressed(evt);
            }
        });
        authors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsActionPerformed(evt);
            }
        });
        add(authors, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        jSeparator10.setForeground(new java.awt.Color(34, 184, 207));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 10));

        isbn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        isbn.setForeground(new java.awt.Color(102, 102, 102));
        isbn.setText("Ingrese el ISBN");
        isbn.setBorder(null);
        isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isbnMousePressed(evt);
            }
        });
        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });
        add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 30));

        jSeparator11.setForeground(new java.awt.Color(34, 184, 207));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 10));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("ISBN");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Editorial");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Stock");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        stock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stock.setForeground(new java.awt.Color(102, 102, 102));
        stock.setText("Ingrese la cantidad de ejemplares");
        stock.setBorder(null);
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockMousePressed(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jSeparator12.setForeground(new java.awt.Color(34, 184, 207));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 260, 10));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Estado");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        state.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        state.setForeground(new java.awt.Color(102, 102, 102));
        state.setText("Ingrese el estado del libro");
        state.setBorder(null);
        state.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stateMousePressed(evt);
            }
        });
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 260, 30));

        jSeparator13.setForeground(new java.awt.Color(34, 184, 207));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 260, 10));

        CboxRecurso.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        CboxRecurso.setName(""); // NOI18N
        CboxRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxRecursoActionPerformed(evt);
            }
        });
        add(CboxRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, -1));

        CboxEditorial.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(CboxEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        if(title.getText().equals("Ingrese el Título"))
        title.setText("");
       if(authors.getText().equals("") || authors.getText() == null || authors.getText().equals(" "))
        authors.setText("Ingrese nombre de autores");
       if(isbn.getText().equals("") || isbn.getText() == null || isbn.getText().equals(" "))
        isbn.setText("Ingrese el ISBN");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Ingrese la cantidad de ejemplares");
       if(state.getText().equals("") || state.getText() == null || state.getText().equals(" "))
        state.setText("Ingrese el estado del libro");
       
    }//GEN-LAST:event_titleMousePressed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void authorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorsMousePressed
        if(authors.getText().equals("Ingrese nombre de autores"))
        authors.setText("");
       if(isbn.getText().equals("") || isbn.getText() == null || isbn.getText().equals(" "))
        isbn.setText("Ingrese el ISBN");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Ingrese la cantidad de ejemplares");
       if(state.getText().equals("") || state.getText() == null || state.getText().equals(" "))
        state.setText("Ingrese el estado del libro");
    }//GEN-LAST:event_authorsMousePressed

    private void authorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorsActionPerformed

    private void isbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isbnMousePressed
        if(isbn.getText().equals("Ingrese el ISBN"))
        isbn.setText("");
       if(authors.getText().equals("") || authors.getText() == null || authors.getText().equals(" "))
        authors.setText("Ingrese nombre de autores");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Ingrese la cantidad de ejemplares");
       if(state.getText().equals("") || state.getText() == null || state.getText().equals(" "))
        state.setText("Ingrese el estado del libro");
      
    }//GEN-LAST:event_isbnMousePressed

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    private void stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMousePressed
        if(stock.getText().equals("Ingrese la cantidad de ejemplares"))
        stock.setText("");
       
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(authors.getText().equals("") || authors.getText() == null || authors.getText().equals(" "))
        authors.setText("Ingrese nombre de autores");
       if(isbn.getText().equals("") || isbn.getText() == null || isbn.getText().equals(" "))
        isbn.setText("Ingrese el ISBN");
       if(state.getText().equals("") || state.getText() == null || state.getText().equals(" "))
        state.setText("Ingrese el estado del libro");
       
    }//GEN-LAST:event_stockMousePressed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    // SUBIR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        BooksFrame p1 = new BooksFrame();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttonMousePressed

    private void stateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateMousePressed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void stateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateMouseClicked
       if(state.getText().equals("Ingrese el estado del libro"))
        state.setText("");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(authors.getText().equals("") || authors.getText() == null || authors.getText().equals(" "))
        authors.setText("Ingrese nombre de autores");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Ingrese la cantidad de ejemplares");
       if(isbn.getText().equals("") || isbn.getText() == null || isbn.getText().equals(" "))
        isbn.setText("Ingrese el ISBN");
    }//GEN-LAST:event_stateMouseClicked

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        
    }//GEN-LAST:event_buttonMouseClicked

    private void CboxRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxRecursoActionPerformed
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,170,191));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(16,152,173));
    }
     private void consultarEditoriales() {
        editoriales = null;
        try (Connection connection = App.getConnection()) {
            EditorialDao editorialDao = App.getEditoriaDao(connection);
//We get a connection stable here
            editoriales = editorialDao.getComboData();
        } 
        catch (Exception ex) {
            System.out.println("Problema cargar Editorial");
        }
        try{
            cargarTblEditoriales();
        }
        catch (Exception e){
            System.out.println("Problema cargarTBLEditoriales");
        }
        
    }
     
     private void consultarTipos() {
        tipo = null;
        try (Connection connection = App.getConnection()) {
            TipoRecursoDao tipoRecursoDao = App.getTipoRecursoDao(connection);
//We get a connection stable here
            tipo = tipoRecursoDao.getComboData();
        } 
        catch (Exception ex) {
            System.out.println("Problema cargar Tipos1");
        }
        try{
            cargarTblEditorialesTipo();
        }
        catch (Exception e){
            System.out.println("Problema cargar tipos2");
        }
        
    }
    private void cargarTblEditorialesTipo() {
        
        if (tipo == null) return;
        
        for (int i = 0; i < tipo.length; i++) {
         
            CboxRecurso.addItem(tipo[i]);
        }
        
    }
    private void cargarTblEditoriales() {
        
        if (editoriales == null) return;
        
        for (int i = 0; i < editoriales.length; i++) {
         
            CboxEditorial.addItem(editoriales[i]);
        }
        
    }
    
   
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxEditorial;
    private javax.swing.JComboBox<String> CboxRecurso;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField authors;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField state;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
